import fs from 'node:fs';
import path from 'node:path';
import { ExaDetector, Vendor } from '../detector/exa_detector.js';
import { VendorIndexer, VendorCallSite } from '../indexer/vendor_indexer.js';
import { GitHubPrService, PullRequestResult } from '../github/pr_service.js';
import { GeminiFixGenerator } from '../fixer/gemini_fix_generator.js';

export interface DemoRun { signal: any; callSites: VendorCallSite[]; matches: VendorCallSite[]; fix: { filePath: string; oldText: string; newText: string; rationale: string }; pr?: PullRequestResult; }

export class CoreLoop {
  constructor(private detector = new ExaDetector(), private indexer = new VendorIndexer(), private github = new GitHubPrService(), private gemini = new GeminiFixGenerator()) {}

  async run(args: { vendor: Vendor; repoDir: string; liveSearch?: boolean; openPr?: boolean; githubRepo?: string; installationId?: number; base?: string }): Promise<DemoRun> {
    const signal = await this.detector.detect(args.vendor, args.liveSearch ?? true);
    const callSites = this.indexer.index(args.repoDir);
    const matches = callSites.filter((s) => this.matches(s.symbol, signal.affectedSymbol));
    if (!matches.length) throw new Error(`No indexed call site matched ${signal.affectedSymbol}`);
    const match = matches[0];
    const fullPath = path.join(args.repoDir, match.filePath);
    const code = fs.readFileSync(fullPath, 'utf8');
    const line = code.split('\n')[match.lineNumber - 1] || match.snippet;
    let fix = this.generateFix(args.vendor, line, signal.affectedSymbol, match.filePath);
    if (process.env.GEMINI_API_KEY) {
      try {
        const generated = await this.gemini.generate({ vendor: args.vendor, symbol: signal.affectedSymbol, summary: signal.summary, filePath: match.filePath, line });
        if (generated) fix = { filePath: match.filePath, ...generated };
      } catch (error) {
        console.warn('Gemini generation failed; using deterministic migration:', error);
      }
    }
    const result: DemoRun = { signal, callSites, matches, fix };
    if (args.openPr) {
      const repo = args.githubRepo || process.env.GITHUB_REPO;
      if (!repo) throw new Error('GITHUB_REPO is required to open a real PR');
      result.pr = await this.openPr({ repo, installationId: args.installationId, base: args.base || 'main', vendor: args.vendor, symbol: signal.affectedSymbol, sourceUrl: signal.sourceUrl, sourceSummary: signal.summary, ...fix });
    }
    return result;
  }

  async openPr(input: { repo: string; installationId?: number; base?: string; vendor: Vendor; symbol: string; sourceUrl: string; sourceSummary: string; filePath: string; oldText: string; newText: string; rationale: string }): Promise<PullRequestResult> {
    return this.github.openPullRequest({
      repo: input.repo, installationId: input.installationId, base: input.base || 'main', filePath: input.filePath, oldText: input.oldText, newText: input.newText,
      branch: `guardian/${input.vendor}-${Date.now()}`,
      title: `fix(${input.vendor}): migrate ${input.symbol}`,
      body: `Automated migration generated by Breaking Change Guardian.\n\n${input.rationale}\n\nSignal: ${input.sourceSummary}\n\nSource: ${input.sourceUrl}`,
    });
  }

  async revise(args: { vendor: Vendor; symbol: string; sourceLine: string; currentLine: string; instruction: string }) {
    return this.gemini.revise(args);
  }

  private matches(actual: string, affected: string): boolean {
    const a = actual.toLowerCase(); const b = affected.toLowerCase();
    return a === b || a.endsWith(b) || b.endsWith(a) || a.startsWith(b + '.') || b.startsWith(a + '.') || (a.includes('sendmessage') && b.includes('sendmessage'));
  }

  private generateFix(_vendor: Vendor, line: string, _symbol: string, filePath: string) {
    const newText = line.replace(/\b([a-zA-Z0-9_$]+)\.sources\.create/g, '$1.paymentMethods.create');
    return { filePath, oldText: line, newText, rationale: 'Migrate the legacy Sources API call to PaymentMethods, the current Stripe integration path.' };
  }
}
